# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 842a41c9347879872b3320a2567023f1d6a23d013e886f443f3f4e91421ec3f1e50d54109b689766bb969c83919d0e387a4c37c270d57a75c803523f192e2a8b

test:
  secret_key_base: 43163da194ab2c31cd18ae196202c13370bfb1197106a1df146aca4bc1e7a5690f26f082514180dfef3b2dc1b950b9b8414893e274d0626c3879787e86b93432

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
